import {
  Banknote,
  Beaker,
  ClipboardCheck,
  Flame,
  GitPullRequestArrow,
  Lightbulb,
  MessageSquareQuote,
  Siren,
} from "lucide-react";
import {
  BudgetTrackerScreen,
  DecisionLogScreen,
  ExperimentsScreen,
  FeedbackHubScreen,
  IncidentCenterScreen,
  ReleaseReadinessScreen,
  RiskRegisterScreen,
} from "./screens/product_addon_screens";

const addonConfigs = [
  {
    id: "risk-register",
    title: "Risks",
    name: "Risk Register",
    category: "Planning",
    icon: Flame,
    color: "#ef4444",
    insertAfter: "Security",
    component: RiskRegisterScreen,
    description: "Track delivery, security, vendor, and scope risks with owners and mitigation progress.",
    features: ["Risk ownership", "Mitigation tracking", "Status filters", "Escalation visibility"],
    actionLabel: "Add risk",
    searchPlaceholder: "Search risks",
    views: ["All", "Open", "Mitigating", "Closed"],
    metrics: [],
    items: [],
  },
  {
    id: "decision-log",
    title: "Decisions",
    name: "Decision Log",
    category: "Governance",
    icon: Lightbulb,
    color: "#f59e0b",
    insertAfter: "Grounding",
    component: DecisionLogScreen,
    description: "Record important product, engineering, and process decisions with context and owners.",
    features: ["Decision history", "Owner assignment", "Review cadence", "Status snapshots"],
    actionLabel: "Add decision",
    searchPlaceholder: "Search decisions",
    views: ["All", "Proposed", "Accepted", "Revisit"],
    metrics: [],
    items: [],
  },
  {
    id: "release-readiness",
    title: "Readiness",
    name: "Release Readiness",
    category: "Delivery",
    icon: ClipboardCheck,
    color: "#10b981",
    insertAfter: "Milestones",
    component: ReleaseReadinessScreen,
    description: "Coordinate launch gates, owners, sign-offs, and outstanding release blockers.",
    features: ["Launch gates", "Sign-off tracking", "Blocker ownership", "Release readiness score"],
    actionLabel: "Add gate",
    searchPlaceholder: "Search launch gates",
    views: ["All", "Blocked", "In Review", "Ready"],
    metrics: [],
    items: [],
  },
  {
    id: "feedback-hub",
    title: "Feedback",
    name: "Customer Feedback Hub",
    category: "Product",
    icon: MessageSquareQuote,
    color: "#06b6d4",
    insertAfter: "Reporting",
    component: FeedbackHubScreen,
    description: "Centralize customer requests, pain points, and feature signals tied to project work.",
    features: ["Feedback triage", "Theme tracking", "Customer impact", "Roadmap links"],
    actionLabel: "Add feedback",
    searchPlaceholder: "Search feedback",
    views: ["All", "New", "Triaged", "Linked"],
    metrics: [],
    items: [],
  },
  {
    id: "experiments",
    title: "Experiments",
    name: "Experiment Tracker",
    category: "Growth",
    icon: Beaker,
    color: "#8b5cf6",
    insertAfter: "Goals",
    component: ExperimentsScreen,
    description: "Plan, run, and evaluate product experiments connected to goals and milestones.",
    features: ["Hypothesis tracking", "Experiment status", "Outcome summaries", "Goal linkage"],
    actionLabel: "Add experiment",
    searchPlaceholder: "Search experiments",
    views: ["All", "Running", "Designing", "Won", "Lost"],
    metrics: [],
    items: [],
  },
  {
    id: "incident-center",
    title: "Incidents",
    name: "Incident Center",
    category: "Operations",
    icon: Siren,
    color: "#ef4444",
    insertAfter: "Logs",
    component: IncidentCenterScreen,
    description: "Manage incidents, response owners, timelines, severity, and postmortem completion.",
    features: ["Incident response", "Severity tracking", "Postmortem status", "Response owners"],
    actionLabel: "Add incident",
    searchPlaceholder: "Search incidents",
    views: ["All", "Active", "Monitoring", "Resolved"],
    metrics: [],
    items: [],
  },
  {
    id: "budget-tracker",
    title: "Budget",
    name: "Budget Tracker",
    category: "Finance",
    icon: Banknote,
    color: "#10b981",
    insertAfter: "Usage",
    component: BudgetTrackerScreen,
    description: "Track project spend, forecasts, vendor costs, and budget variance before it surprises the team.",
    features: ["Budget rollups", "Spend forecasting", "Vendor line items", "Variance tracking"],
    actionLabel: "Add cost",
    searchPlaceholder: "Search budget",
    views: ["All", "On Track", "Watch", "Over"],
    metrics: [],
    items: [],
  },
];

function makeAddon(config) {
  const AddonScreen = config.component;

  return {
    id: config.id,
    name: config.name,
    description: config.description,
    version: "1.0.0",
    category: config.category,
    icon: config.icon,
    color: config.color,
    features: config.features,
    navItem: {
      title: config.title,
      icon: config.icon,
      insertAfter: config.insertAfter,
    },
    screens: [
      {
        id: config.title,
        component: AddonScreen,
      },
    ],
  };
}

export const projectPlusAddons = addonConfigs.map(makeAddon);
export const projectPlusAddonIds = projectPlusAddons.map((addon) => addon.id);
