import {
  Banknote,
  Beaker,
  ClipboardCheck,
  Flame,
  GitPullRequestArrow,
  Lightbulb,
  MessageSquareQuote,
  Siren,
} from "lucide-react";
import { AddonWorkspaceScreen } from "./screens/addon_workspace_screen";

const addonConfigs = [
  {
    id: "risk-register",
    title: "Risks",
    name: "Risk Register",
    category: "Planning",
    icon: Flame,
    color: "#ef4444",
    insertAfter: "Security",
    description: "Track delivery, security, vendor, and scope risks with owners and mitigation progress.",
    features: ["Risk ownership", "Mitigation tracking", "Status filters", "Escalation visibility"],
    actionLabel: "Add risk",
    searchPlaceholder: "Search risks",
    views: ["All", "Open", "Mitigating", "Closed"],
    metrics: [
      { label: "Open risks", value: "5", detail: "2 high impact", icon: Flame },
      { label: "Mitigating", value: "3", detail: "Active owners", icon: ClipboardCheck },
      { label: "Due this week", value: "2", detail: "Review needed", icon: Siren },
      { label: "Closed", value: "8", detail: "This quarter", icon: Lightbulb },
    ],
    items: [
      {
        code: "RSK-12",
        title: "Staging data drift can delay release validation",
        description: "Refresh cadence is inconsistent between staging and production-like datasets.",
        owner: "Priya Shah",
        due: "May 14",
        status: "Mitigating",
        statusTone: "amber",
        signalLabel: "Impact",
        signal: "High",
        progress: 55,
        view: "Mitigating",
      },
      {
        code: "RSK-09",
        title: "Vendor SLA not confirmed for launch week",
        description: "Support window is not yet contractually confirmed with the integration vendor.",
        owner: "Sam Lee",
        due: "May 17",
        status: "Open",
        statusTone: "red",
        signalLabel: "Impact",
        signal: "Medium",
        progress: 20,
        view: "Open",
      },
      {
        code: "RSK-05",
        title: "Mobile regression scope reduced",
        description: "QA agreed on a narrower test matrix after device analytics review.",
        owner: "Aadit Joshi",
        due: "Done",
        status: "Closed",
        statusTone: "emerald",
        signalLabel: "Impact",
        signal: "Low",
        progress: 100,
        view: "Closed",
      },
    ],
  },
  {
    id: "decision-log",
    title: "Decisions",
    name: "Decision Log",
    category: "Governance",
    icon: Lightbulb,
    color: "#f59e0b",
    insertAfter: "Grounding",
    description: "Record important product, engineering, and process decisions with context and owners.",
    features: ["Decision history", "Owner assignment", "Review cadence", "Status snapshots"],
    actionLabel: "Add decision",
    searchPlaceholder: "Search decisions",
    views: ["All", "Proposed", "Accepted", "Revisit"],
    metrics: [
      { label: "Accepted", value: "14", detail: "Current quarter", icon: ClipboardCheck },
      { label: "Proposed", value: "3", detail: "Awaiting review", icon: Lightbulb },
      { label: "Revisit", value: "2", detail: "Needs context", icon: MessageSquareQuote },
      { label: "Owners", value: "6", detail: "Across teams", icon: GitPullRequestArrow },
    ],
    items: [
      {
        code: "DEC-31",
        title: "Keep saved views local until report queries stabilize",
        description: "Avoid persisting view configuration before the reporting data contract is settled.",
        owner: "Aadit Joshi",
        due: "May 13",
        status: "Accepted",
        statusTone: "emerald",
        signalLabel: "Scope",
        signal: "Reporting",
        progress: 100,
        view: "Accepted",
      },
      {
        code: "DEC-30",
        title: "Use role-based access for vault entries",
        description: "Vault secrets should default to role access, with user exceptions only when needed.",
        owner: "Sam Lee",
        due: "May 15",
        status: "Proposed",
        statusTone: "blue",
        signalLabel: "Scope",
        signal: "Security",
        progress: 60,
        view: "Proposed",
      },
      {
        code: "DEC-22",
        title: "Revisit custom field schema after beta",
        description: "The schema works for beta, but may need typed constraints after usage data arrives.",
        owner: "Priya Shah",
        due: "Jun 3",
        status: "Revisit",
        statusTone: "amber",
        signalLabel: "Scope",
        signal: "Platform",
        progress: 35,
        view: "Revisit",
      },
    ],
  },
  {
    id: "release-readiness",
    title: "Readiness",
    name: "Release Readiness",
    category: "Delivery",
    icon: ClipboardCheck,
    color: "#10b981",
    insertAfter: "Milestones",
    description: "Coordinate launch gates, owners, sign-offs, and outstanding release blockers.",
    features: ["Launch gates", "Sign-off tracking", "Blocker ownership", "Release readiness score"],
    actionLabel: "Add gate",
    searchPlaceholder: "Search launch gates",
    views: ["All", "Blocked", "In Review", "Ready"],
    metrics: [
      { label: "Ready gates", value: "7", detail: "Of 10 gates", icon: ClipboardCheck },
      { label: "Blocked", value: "1", detail: "Needs owner", icon: Siren },
      { label: "In review", value: "2", detail: "Awaiting sign-off", icon: GitPullRequestArrow },
      { label: "Readiness", value: "78%", detail: "Launch score", icon: Beaker },
    ],
    items: [
      {
        code: "REL-08",
        title: "Production rollback checklist approved",
        description: "Rollback owners and runbook actions are reviewed for launch week.",
        owner: "Alex Morgan",
        due: "May 13",
        status: "Ready",
        statusTone: "emerald",
        signalLabel: "Gate",
        signal: "Ops",
        progress: 100,
        view: "Ready",
      },
      {
        code: "REL-06",
        title: "Support macro updates pending",
        description: "Customer support macros still need final product copy review.",
        owner: "Priya Shah",
        due: "May 15",
        status: "In Review",
        statusTone: "blue",
        signalLabel: "Gate",
        signal: "Support",
        progress: 70,
        view: "In Review",
      },
      {
        code: "REL-04",
        title: "Final mobile regression pass blocked",
        description: "QA needs the latest staging build before completing mobile validation.",
        owner: "Riley Park",
        due: "Today",
        status: "Blocked",
        statusTone: "red",
        signalLabel: "Gate",
        signal: "QA",
        progress: 45,
        view: "Blocked",
      },
    ],
  },
  {
    id: "feedback-hub",
    title: "Feedback",
    name: "Customer Feedback Hub",
    category: "Product",
    icon: MessageSquareQuote,
    color: "#06b6d4",
    insertAfter: "Reporting",
    description: "Centralize customer requests, pain points, and feature signals tied to project work.",
    features: ["Feedback triage", "Theme tracking", "Customer impact", "Roadmap links"],
    actionLabel: "Add feedback",
    searchPlaceholder: "Search feedback",
    views: ["All", "New", "Triaged", "Linked"],
    metrics: [
      { label: "New signals", value: "18", detail: "This week", icon: MessageSquareQuote },
      { label: "Triaged", value: "11", detail: "Ready for planning", icon: ClipboardCheck },
      { label: "Linked", value: "7", detail: "Tied to work", icon: GitPullRequestArrow },
      { label: "Top theme", value: "Speed", detail: "6 mentions", icon: Beaker },
    ],
    items: [
      {
        code: "FDB-44",
        title: "Bulk task updates are too slow for PM workflows",
        description: "Three customers reported friction updating task statuses across large projects.",
        owner: "Priya Shah",
        due: "May 16",
        status: "Triaged",
        statusTone: "blue",
        signalLabel: "Impact",
        signal: "6 accounts",
        progress: 65,
        view: "Triaged",
      },
      {
        code: "FDB-39",
        title: "Need CSV export from reporting views",
        description: "Enterprise admins want weekly reporting exports for compliance packs.",
        owner: "Aadit Joshi",
        due: "May 20",
        status: "Linked",
        statusTone: "emerald",
        signalLabel: "Impact",
        signal: "Enterprise",
        progress: 80,
        view: "Linked",
      },
      {
        code: "FDB-35",
        title: "Calendar view should show blocked tasks",
        description: "Beta users need blocked work surfaced earlier in planning sessions.",
        owner: "Sam Lee",
        due: "May 18",
        status: "New",
        statusTone: "amber",
        signalLabel: "Impact",
        signal: "Beta",
        progress: 25,
        view: "New",
      },
    ],
  },
  {
    id: "experiments",
    title: "Experiments",
    name: "Experiment Tracker",
    category: "Growth",
    icon: Beaker,
    color: "#8b5cf6",
    insertAfter: "Goals",
    description: "Plan, run, and evaluate product experiments connected to goals and milestones.",
    features: ["Hypothesis tracking", "Experiment status", "Outcome summaries", "Goal linkage"],
    actionLabel: "Add experiment",
    searchPlaceholder: "Search experiments",
    views: ["All", "Running", "Designing", "Won", "Lost"],
    metrics: [
      { label: "Running", value: "3", detail: "Live tests", icon: Beaker },
      { label: "Win rate", value: "42%", detail: "Last 12 tests", icon: ClipboardCheck },
      { label: "Designing", value: "4", detail: "Queued ideas", icon: Lightbulb },
      { label: "Impact", value: "+8%", detail: "Activation lift", icon: GitPullRequestArrow },
    ],
    items: [
      {
        code: "EXP-18",
        title: "Shorter onboarding checklist",
        description: "Test if fewer starter steps improve activation without lowering project quality.",
        owner: "Priya Shah",
        due: "May 22",
        status: "Running",
        statusTone: "violet",
        signalLabel: "Metric",
        signal: "Activation",
        progress: 58,
        view: "Running",
      },
      {
        code: "EXP-15",
        title: "Inline reporting export CTA",
        description: "Expose export action beside saved views for admin users.",
        owner: "Aadit Joshi",
        due: "May 19",
        status: "Designing",
        statusTone: "blue",
        signalLabel: "Metric",
        signal: "Exports",
        progress: 35,
        view: "Designing",
      },
      {
        code: "EXP-11",
        title: "Default grouped task list",
        description: "Grouping by due date improved weekly task completion for pilot teams.",
        owner: "Sam Lee",
        due: "Done",
        status: "Won",
        statusTone: "emerald",
        signalLabel: "Metric",
        signal: "+11%",
        progress: 100,
        view: "Won",
      },
    ],
  },
  {
    id: "incident-center",
    title: "Incidents",
    name: "Incident Center",
    category: "Operations",
    icon: Siren,
    color: "#ef4444",
    insertAfter: "Logs",
    description: "Manage incidents, response owners, timelines, severity, and postmortem completion.",
    features: ["Incident response", "Severity tracking", "Postmortem status", "Response owners"],
    actionLabel: "Add incident",
    searchPlaceholder: "Search incidents",
    views: ["All", "Active", "Monitoring", "Resolved"],
    metrics: [
      { label: "Active", value: "1", detail: "SEV-2", icon: Siren },
      { label: "Monitoring", value: "2", detail: "Stable", icon: ClipboardCheck },
      { label: "MTTR", value: "38m", detail: "Last 30 days", icon: Beaker },
      { label: "Postmortems", value: "4", detail: "Completed", icon: Lightbulb },
    ],
    items: [
      {
        code: "INC-27",
        title: "Webhook delivery latency above threshold",
        description: "Queue delay exceeded SLO for enterprise webhook consumers.",
        owner: "Sam Lee",
        due: "Now",
        status: "Active",
        statusTone: "red",
        signalLabel: "Severity",
        signal: "SEV-2",
        progress: 35,
        view: "Active",
      },
      {
        code: "INC-24",
        title: "Asset thumbnails regenerated slowly",
        description: "Background workers recovered after scaling the media queue.",
        owner: "Riley Park",
        due: "Today",
        status: "Monitoring",
        statusTone: "amber",
        signalLabel: "Severity",
        signal: "SEV-3",
        progress: 78,
        view: "Monitoring",
      },
      {
        code: "INC-19",
        title: "Search indexing gap after deploy",
        description: "Search index rebuild completed and postmortem actions were filed.",
        owner: "Aadit Joshi",
        due: "Done",
        status: "Resolved",
        statusTone: "emerald",
        signalLabel: "Severity",
        signal: "SEV-3",
        progress: 100,
        view: "Resolved",
      },
    ],
  },
  {
    id: "budget-tracker",
    title: "Budget",
    name: "Budget Tracker",
    category: "Finance",
    icon: Banknote,
    color: "#10b981",
    insertAfter: "Usage",
    description: "Track project spend, forecasts, vendor costs, and budget variance before it surprises the team.",
    features: ["Budget rollups", "Spend forecasting", "Vendor line items", "Variance tracking"],
    actionLabel: "Add cost",
    searchPlaceholder: "Search budget",
    views: ["All", "On Track", "Watch", "Over"],
    metrics: [
      { label: "Budget used", value: "68%", detail: "$34k of $50k", icon: Banknote },
      { label: "Forecast", value: "$47k", detail: "Month end", icon: ClipboardCheck },
      { label: "Watch items", value: "2", detail: "Cloud + QA", icon: Siren },
      { label: "Variance", value: "-6%", detail: "Under plan", icon: Beaker },
    ],
    items: [
      {
        code: "BDG-10",
        title: "Cloud preview environments",
        description: "Ephemeral previews increased spend after parallel QA cycles.",
        owner: "Alex Morgan",
        due: "May 15",
        status: "Watch",
        statusTone: "amber",
        signalLabel: "Forecast",
        signal: "$9.2k",
        progress: 72,
        view: "Watch",
      },
      {
        code: "BDG-08",
        title: "Design contractor allocation",
        description: "Contractor hours are aligned to milestone budget after scope review.",
        owner: "Priya Shah",
        due: "May 24",
        status: "On Track",
        statusTone: "emerald",
        signalLabel: "Forecast",
        signal: "$6.5k",
        progress: 60,
        view: "On Track",
      },
      {
        code: "BDG-06",
        title: "Security audit reserve",
        description: "Reserve has room for one follow-up penetration test cycle.",
        owner: "Sam Lee",
        due: "Jun 1",
        status: "On Track",
        statusTone: "emerald",
        signalLabel: "Forecast",
        signal: "$12k",
        progress: 45,
        view: "On Track",
      },
    ],
  },
];

function makeAddon(config) {
  function AddonScreen() {
    return <AddonWorkspaceScreen config={config} />;
  }

  return {
    id: config.id,
    name: config.name,
    description: config.description,
    version: "1.0.0",
    category: config.category,
    icon: config.icon,
    color: config.color,
    features: config.features,
    navItem: {
      title: config.title,
      icon: config.icon,
      insertAfter: config.insertAfter,
    },
    screens: [
      {
        id: config.title,
        component: AddonScreen,
      },
    ],
  };
}

export const projectPlusAddons = addonConfigs.map(makeAddon);
export const projectPlusAddonIds = projectPlusAddons.map((addon) => addon.id);
