-- ===========================================================================
-- DEPRECATED — Flow forms tables have been retired.
-- ===========================================================================
-- Geiger Forms now owns the forms domain through geiger_forms,
-- geiger_form_responses, geiger_form_versions, and geiger_form_comments
-- with nullable project_id scoping to flow_projects.
--
-- See geiger-forms/supabase/sqls/forms.sql and collaboration.sql for the
-- current schema. See EXTERNAL_PRODUCT_TABLES.md for the migration plan.
-- ===========================================================================
