// Fixture rows for the landing playground.
//
// One project — "Apollo Platform Redesign" — described consistently across every
// table the workspace screens read, so the embed behaves like a real workspace:
// an issue's assignee is a real project_members row, a milestone's tasks match
// real tasks, and the Overview's charts have a fortnight of activity to draw.
//
// Rows carry DB column names (snake_case), exactly as PostgREST would return
// them — the data layer's normalize* functions do the camelCase mapping, so
// fixturing at the column boundary keeps the whole pipeline under test.
//
// Ids are stable and hard-coded, and they are valid v4-shaped UUIDs because
// ProjectProvider gates on a UUID pattern before it will load a project.
//
// Timestamps are relative to module load so the demo always looks current. The
// playground screens are client-only (dynamic + ssr:false), so these values are
// never rendered on the server and cannot cause a hydration mismatch.

const SEED = {
  organization: "c2d3e4f5",
  project: "b1c2d3e4",
  user: "a9e0f1c2",
  member: "5f607182",
  objective: "2c3d4e5f",
  goal: "1b2c3d4e",
  milestone: "3d4e5f60",
  issue: "d3e4f5a6",
  issueComment: "e4f5a6b7",
  task: "f5a6b7c8",
  taskComment: "0a1b2c3d",
  asset: "4e5f6071",
  log: "60718293",
  allocation: "718293a4",
  link: "8293a4b5",
  notification: "93a4b5c6",
};

const id = (key, n) =>
  `${SEED[key]}-0000-4000-8000-${String(n).padStart(12, "0")}`;

const DAY = 86400000;
const at = (days) => new Date(Date.now() + days * DAY).toISOString();
const daysAgo = (n) => at(-n);
// Date-only columns (due_date, target_date, starts_on…) want YYYY-MM-DD.
const dateIn = (days) => at(days).slice(0, 10);

export const DEMO_ORGANIZATION_ID = id("organization", 1);

const PROJECT_ID = id("project", 1);

// The team. Everything that names a person — issue assignees, task owners,
// activity actors, milestone owners — points back into this list, so the
// assignee pickers, avatars and member table all resolve to the same six people.
const PEOPLE = [
  { id: id("user", 101), name: "Ada Whitfield", email: "ada@geiger.studio", title: "Design Lead" },
  { id: id("user", 102), name: "Marcus Ibe", email: "marcus@geiger.studio", title: "Engineering Lead" },
  { id: id("user", 103), name: "Priya Raman", email: "priya@geiger.studio", title: "Platform Engineer" },
  { id: id("user", 104), name: "Tomás Ferreira", email: "tomas@geiger.studio", title: "Frontend Engineer" },
  { id: id("user", 105), name: "Lena Kovač", email: "lena@geiger.studio", title: "QA Engineer" },
  { id: id("user", 106), name: "Sam Okafor", email: "sam@geiger.studio", title: "Product Manager" },
];

const [ADA, MARCUS, PRIYA, TOMAS, LENA, SAM] = PEOPLE;

// project_members rows, one per person. `metadata.authorName` is what
// normalizeMember reads for the display name (it falls back to the email
// prefix), so it has to carry the full name.
const PROJECT_MEMBERS = PEOPLE.map((person, index) => ({
  id: id("member", 201 + index),
  project_id: PROJECT_ID,
  user_id: person.id,
  email: person.email,
  role: index === 0 || index === 5 ? "admin" : "member",
  status: "Active",
  metadata: { authorName: person.name },
  created_by: ADA.id,
  created_at: daysAgo(120 - index),
  updated_at: daysAgo(120 - index),
  deleted_at: null,
}));

const OBJECTIVES = [
  {
    id: id("objective", 1),
    project_id: PROJECT_ID,
    title: "Ship the Apollo design system v2",
    description:
      "Replace the ad-hoc component styles with one token-driven system that both the marketing site and the product consume.",
    status: "on_track",
    owner: ADA.name,
    progress: 62,
    start_date: dateIn(-60),
    target_date: dateIn(45),
    metadata: {
      keyResults: [
        { label: "100% of surfaces on v2 tokens", progress: 68, done: false },
        { label: "Component library published", progress: 55, done: false },
        { label: "Legacy styles deleted", progress: 30, done: false },
      ],
    },
    created_by: ADA.id,
    created_at: daysAgo(60),
    updated_at: daysAgo(2),
    deleted_at: null,
  },
  {
    id: id("objective", 2),
    project_id: PROJECT_ID,
    title: "Cut time-to-first-value to under 5 minutes",
    description:
      "A new account should reach a working board without reading documentation or waiting on an invite.",
    status: "at_risk",
    owner: SAM.name,
    progress: 34,
    start_date: dateIn(-45),
    target_date: dateIn(30),
    metadata: {
      keyResults: [
        { label: "Onboarding reduced to 3 steps", progress: 40, done: false },
        { label: "Empty states on every first-run surface", progress: 25, done: false },
        { label: "Median TTFT under 5 minutes", progress: 38, done: false },
      ],
    },
    created_by: SAM.id,
    created_at: daysAgo(45),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
];

const GOALS = [
  {
    id: id("goal", 1),
    project_id: PROJECT_ID,
    objective_id: id("objective", 1),
    title: "Adopt tokens across 100% of product surfaces",
    description: "Every background, border and text colour resolves to a semantic token — no raw hex.",
    status: "on_track",
    owner: ADA.name,
    progress: 68,
    target_date: dateIn(40),
    position: 0,
    metadata: {
      keyResults: [
        { label: "Dashboard migrated", progress: 100, done: true },
        { label: "Project workspace migrated", progress: 72, done: false },
        { label: "Marketing site migrated", progress: 30, done: false },
      ],
      progressSource: "tasks_lists",
      trackMetric: "tasks_count",
      target: "dynamic",
      targetValue: "",
    },
    created_by: ADA.id,
    created_at: daysAgo(58),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("goal", 2),
    project_id: PROJECT_ID,
    objective_id: id("objective", 1),
    title: "Publish the v2 component library",
    description: "One documented, versioned package that every product in the suite installs.",
    status: "on_track",
    owner: TOMAS.name,
    progress: 55,
    target_date: dateIn(55),
    position: 1,
    metadata: {
      keyResults: [
        { label: "Storybook deployed", progress: 80, done: false },
        { label: "API docs written", progress: 45, done: false },
        { label: "First downstream product migrated", progress: 20, done: false },
      ],
      progressSource: "tasks_lists",
      trackMetric: "tasks_count",
      target: "dynamic",
      targetValue: "",
    },
    created_by: TOMAS.id,
    created_at: daysAgo(52),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
  {
    id: id("goal", 3),
    project_id: PROJECT_ID,
    objective_id: id("objective", 2),
    title: "Reduce onboarding to three steps",
    description: "Sign up, name the project, invite the team. Nothing else before the first board.",
    status: "at_risk",
    owner: SAM.name,
    progress: 40,
    target_date: dateIn(28),
    position: 0,
    metadata: {
      keyResults: [
        { label: "Provider step made optional", progress: 100, done: true },
        { label: "Template picker removed", progress: 50, done: false },
        { label: "Invite step deferred to first share", progress: 15, done: false },
      ],
      progressSource: "tasks_lists",
      trackMetric: "tasks_count",
      target: "dynamic",
      targetValue: "",
    },
    created_by: SAM.id,
    created_at: daysAgo(44),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: id("goal", 4),
    project_id: PROJECT_ID,
    objective_id: id("objective", 2),
    title: "First-run empty states on every surface",
    description: "No screen ever greets a new account with a blank table.",
    status: "not_started",
    owner: ADA.name,
    progress: 0,
    target_date: dateIn(50),
    position: 1,
    metadata: {
      keyResults: [
        { label: "Illustration set delivered", progress: 0, done: false },
        { label: "Copy reviewed", progress: 0, done: false },
      ],
      progressSource: "tasks_lists",
      trackMetric: "tasks_count",
      target: "dynamic",
      targetValue: "",
    },
    created_by: ADA.id,
    created_at: daysAgo(30),
    updated_at: daysAgo(30),
    deleted_at: null,
  },
  {
    id: id("goal", 5),
    project_id: PROJECT_ID,
    objective_id: null,
    title: "Design QA gate in CI",
    description: "Visual diffs block a merge, so a token regression cannot reach main.",
    status: "on_track",
    owner: LENA.name,
    progress: 70,
    target_date: dateIn(21),
    position: 0,
    metadata: {
      keyResults: [
        { label: "Visual diff runner in CI", progress: 100, done: true },
        { label: "Baseline snapshots for core screens", progress: 60, done: false },
      ],
      progressSource: "tasks_lists",
      trackMetric: "tasks_count",
      target: "dynamic",
      targetValue: "",
    },
    created_by: LENA.id,
    created_at: daysAgo(38),
    updated_at: daysAgo(2),
    deleted_at: null,
  },
];

const MILESTONES = [
  {
    id: id("milestone", 1),
    project_id: PROJECT_ID,
    title: "Design system v2 — beta",
    description: "Tokens frozen, core components migrated, published to the internal registry.",
    owner: ADA.name,
    target_date: dateIn(12),
    metadata: {
      tasks: [
        { id: "mt_1", title: "Freeze the token contract", status: "done", assignee: ADA.name },
        { id: "mt_2", title: "Migrate the workspace shell", status: "in_progress", assignee: TOMAS.name },
        { id: "mt_3", title: "Publish the beta package", status: "todo", assignee: TOMAS.name },
        { id: "mt_4", title: "Accessibility sweep", status: "todo", assignee: LENA.name },
      ],
    },
    created_by: ADA.id,
    created_at: daysAgo(50),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("milestone", 2),
    project_id: PROJECT_ID,
    title: "Onboarding rewrite live",
    description: "Three-step signup behind a flag, with first-run empty states on the board screens.",
    owner: SAM.name,
    target_date: dateIn(34),
    metadata: {
      tasks: [
        { id: "mt_5", title: "Provider step made optional", status: "done", assignee: MARCUS.name },
        { id: "mt_6", title: "Invite moved to first share", status: "in_progress", assignee: MARCUS.name },
        { id: "mt_7", title: "Empty-state illustrations", status: "blocked", assignee: ADA.name },
      ],
    },
    created_by: SAM.id,
    created_at: daysAgo(40),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
  {
    id: id("milestone", 3),
    project_id: PROJECT_ID,
    title: "Performance budget enforced",
    description: "JavaScript budget in CI, chart and table code split off the critical path.",
    owner: PRIYA.name,
    target_date: dateIn(58),
    metadata: {
      tasks: [
        { id: "mt_8", title: "Measure the current bundle", status: "done", assignee: PRIYA.name },
        { id: "mt_9", title: "Split the chart bundle", status: "in_progress", assignee: TOMAS.name },
        { id: "mt_10", title: "Fail the build over budget", status: "todo", assignee: PRIYA.name },
      ],
    },
    created_by: PRIYA.id,
    created_at: daysAgo(26),
    updated_at: daysAgo(5),
    deleted_at: null,
  },
];

// Issue metadata is uniform so the detail view never sees a half-shaped bag.
const issueMeta = (over = {}) => ({
  type: over.type ?? "task",
  estimate: over.estimate ?? "",
  startDate: over.startDate ?? null,
  watchers: over.watchers ?? [],
  archived: over.archived ?? false,
  archivedAt: over.archivedAt ?? null,
  attachments: over.attachments ?? [],
  cycleId: over.cycleId ?? null,
  objectiveId: over.objectiveId ?? null,
});

const ISSUES = [
  {
    id: id("issue", 1),
    number: 1,
    project_id: PROJECT_ID,
    title: "Sidebar collapses at tablet breakpoints",
    description:
      "Between 768px and 1024px the project sidebar collapses to icons on load and never expands, so the nav labels are unreachable until a manual toggle.",
    status: "open",
    priority: "high",
    labels: ["ui", "regression"],
    assignee_ids: [TOMAS.id],
    due_date: dateIn(3),
    parent_id: null,
    metadata: issueMeta({ type: "bug", estimate: "3h", objectiveId: id("objective", 2) }),
    created_by: LENA.id,
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("issue", 2),
    number: 2,
    project_id: PROJECT_ID,
    title: "Token values drift between light and dark",
    description:
      "Three surface tokens resolve to different raw values in dark mode, so cards sit at two different elevations depending on the screen.",
    status: "in_progress",
    priority: "critical",
    labels: ["tokens", "a11y"],
    assignee_ids: [ADA.id, TOMAS.id],
    due_date: dateIn(2),
    parent_id: null,
    metadata: issueMeta({ type: "bug", estimate: "5h", objectiveId: id("objective", 1) }),
    created_by: ADA.id,
    created_at: daysAgo(11),
    updated_at: daysAgo(0),
    deleted_at: null,
  },
  {
    id: id("issue", 3),
    number: 3,
    project_id: PROJECT_ID,
    title: "Keyboard shortcuts in the command palette",
    description: "Support arrow navigation, enter to run and escape to dismiss without leaving the input.",
    status: "open",
    priority: "medium",
    labels: ["dx"],
    assignee_ids: [MARCUS.id],
    due_date: dateIn(9),
    parent_id: null,
    metadata: issueMeta({ type: "feature", estimate: "1d" }),
    created_by: MARCUS.id,
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: id("issue", 4),
    number: 4,
    project_id: PROJECT_ID,
    title: "Export a component usage report as CSV",
    description: "Product wants a per-project rollup of which v2 components are in use, to plan the legacy cleanup.",
    status: "open",
    priority: "low",
    labels: ["reporting"],
    assignee_ids: [PRIYA.id],
    due_date: dateIn(24),
    parent_id: null,
    metadata: issueMeta({ type: "improvement", objectiveId: id("objective", 1) }),
    created_by: SAM.id,
    created_at: daysAgo(9),
    updated_at: daysAgo(9),
    deleted_at: null,
  },
  {
    id: id("issue", 5),
    number: 5,
    project_id: PROJECT_ID,
    title: "Focus ring invisible on the primary button",
    description: "The ring colour matched the fill, so keyboard focus was invisible against the primary surface.",
    status: "resolved",
    priority: "high",
    labels: ["a11y", "regression"],
    assignee_ids: [LENA.id],
    due_date: dateIn(-2),
    parent_id: null,
    metadata: issueMeta({ type: "bug", objectiveId: id("objective", 1) }),
    created_by: LENA.id,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
    deleted_at: null,
  },
  {
    id: id("issue", 6),
    number: 6,
    project_id: PROJECT_ID,
    title: "Document the spacing scale",
    description: "Write down why the scale is 4-based and where the two half-steps are allowed.",
    status: "resolved",
    priority: "low",
    labels: ["docs"],
    assignee_ids: [ADA.id],
    due_date: dateIn(-5),
    parent_id: id("issue", 2),
    metadata: issueMeta({ type: "chore", objectiveId: id("objective", 1) }),
    created_by: ADA.id,
    created_at: daysAgo(21),
    updated_at: daysAgo(6),
    deleted_at: null,
  },
  {
    id: id("issue", 7),
    number: 7,
    project_id: PROJECT_ID,
    title: "Chart tooltips clip at the card edge",
    description: "A tooltip on the rightmost data point is cut off by the card's overflow, so the value is unreadable.",
    status: "in_progress",
    priority: "medium",
    labels: ["charts", "ui"],
    assignee_ids: [TOMAS.id],
    due_date: dateIn(6),
    parent_id: null,
    metadata: issueMeta({ type: "bug", estimate: "4h" }),
    created_by: TOMAS.id,
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("issue", 8),
    number: 8,
    project_id: PROJECT_ID,
    title: "Reduce the initial bundle by 200 KB",
    description: "Charts and the table virtualiser both load on first paint though neither is visible above the fold.",
    status: "open",
    priority: "high",
    labels: ["performance"],
    assignee_ids: [PRIYA.id],
    due_date: dateIn(15),
    parent_id: null,
    metadata: issueMeta({ type: "improvement", estimate: "2d" }),
    created_by: PRIYA.id,
    created_at: daysAgo(13),
    updated_at: daysAgo(5),
    deleted_at: null,
  },
  {
    id: id("issue", 9),
    number: 9,
    project_id: PROJECT_ID,
    title: "Consolidate icon imports",
    description: "Icon packages are imported per-file, so the same glyph ships in several chunks.",
    status: "open",
    priority: "low",
    labels: ["performance"],
    assignee_ids: [MARCUS.id],
    due_date: dateIn(20),
    parent_id: id("issue", 8),
    metadata: issueMeta({ type: "chore" }),
    created_by: MARCUS.id,
    created_at: daysAgo(12),
    updated_at: daysAgo(8),
    deleted_at: null,
  },
  {
    id: id("issue", 10),
    number: 10,
    project_id: PROJECT_ID,
    title: "Add a dark-mode contrast test",
    description: "Every semantic pairing should be asserted at AA contrast in both themes, in CI.",
    status: "open",
    priority: "critical",
    labels: ["a11y", "testing"],
    assignee_ids: [LENA.id],
    due_date: dateIn(7),
    parent_id: null,
    metadata: issueMeta({ type: "task", estimate: "1d", objectiveId: id("objective", 1) }),
    created_by: LENA.id,
    created_at: daysAgo(5),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
  {
    id: id("issue", 11),
    number: 11,
    project_id: PROJECT_ID,
    title: "Migrate the legacy modals to the shared Dialog",
    description: "Four screens still carry their own overlay, with a second close button and no focus trap.",
    status: "in_progress",
    priority: "medium",
    labels: ["ui"],
    assignee_ids: [TOMAS.id, MARCUS.id],
    due_date: dateIn(11),
    parent_id: null,
    metadata: issueMeta({ type: "improvement", estimate: "1d", objectiveId: id("objective", 1) }),
    created_by: TOMAS.id,
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("issue", 12),
    number: 12,
    project_id: PROJECT_ID,
    title: "Token naming review",
    description: "Decide once whether elevation tokens are named by rank or by purpose, then rename in one pass.",
    status: "resolved",
    priority: "medium",
    labels: ["tokens", "docs"],
    assignee_ids: [ADA.id, SAM.id],
    due_date: dateIn(-8),
    parent_id: id("issue", 2),
    metadata: issueMeta({ type: "task", objectiveId: id("objective", 1) }),
    created_by: ADA.id,
    created_at: daysAgo(24),
    updated_at: daysAgo(9),
    deleted_at: null,
  },
];

const ISSUE_COMMENTS = [
  {
    id: id("issueComment", 1),
    issue_id: id("issue", 2),
    author_id: TOMAS.id,
    body: "Reproduced on the project workspace — the card and the table shell end up on different elevations. Both come from the same token, so the lookup is resolving differently per theme.",
    attachments: [],
    created_at: daysAgo(8),
    updated_at: daysAgo(8),
  },
  {
    id: id("issueComment", 2),
    issue_id: id("issue", 2),
    author_id: ADA.id,
    body: "That matches what I saw. Fix is to collapse the two aliases onto one ranked token — I'll pick the naming in #12 and land the migration behind it.",
    attachments: [],
    created_at: daysAgo(6),
    updated_at: daysAgo(6),
  },
  {
    id: id("issueComment", 3),
    issue_id: id("issue", 2),
    author_id: LENA.id,
    body: "Contrast passes on the fixed pair, so the accessibility side is clear either way.",
    attachments: [],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: id("issueComment", 4),
    issue_id: id("issue", 1),
    author_id: TOMAS.id,
    body: "The collapse-on-load is the persisted sidebar state being read before the breakpoint listener attaches. Narrow fix, but I want a regression test with it.",
    attachments: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: id("issueComment", 5),
    issue_id: id("issue", 11),
    author_id: MARCUS.id,
    body: "Two of the four are one-line swaps. The billing and invite flows each carry custom copy, so those need a second pass.",
    attachments: [],
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
  },
];

const TASKS = [
  {
    id: id("task", 1),
    project_id: PROJECT_ID,
    title: "Audit legacy button components",
    description: "Catalogue every button variant in use and map each onto a v2 counterpart.",
    status: "done",
    priority: "high",
    stage: "review",
    type: "task",
    progress: 100,
    labels: ["audit"],
    assignee_ids: [TOMAS.id],
    parent_link: id("goal", 1),
    start_date: dateIn(-24),
    due_date: dateIn(-14),
    deadline_tracking: true,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(24),
    updated_at: daysAgo(6),
    deleted_at: null,
  },
  {
    id: id("task", 2),
    project_id: PROJECT_ID,
    title: "Define the colour token contract",
    description: "One name per role, ranked surfaces, no purpose aliases.",
    status: "done",
    priority: "critical",
    stage: "review",
    type: "feature",
    progress: 100,
    labels: ["tokens"],
    assignee_ids: [ADA.id],
    parent_link: id("goal", 1),
    start_date: dateIn(-30),
    due_date: dateIn(-18),
    deadline_tracking: true,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(30),
    updated_at: daysAgo(9),
    deleted_at: null,
  },
  {
    id: id("task", 3),
    project_id: PROJECT_ID,
    title: "Migrate tokens to CSS variables",
    description: "Swap every hard-coded surface for its semantic variable, screen by screen.",
    status: "in_progress",
    priority: "high",
    stage: "execution",
    type: "task",
    progress: 65,
    labels: ["tokens", "ui"],
    assignee_ids: [TOMAS.id],
    parent_link: id("goal", 1),
    start_date: dateIn(-12),
    due_date: dateIn(5),
    deadline_tracking: true,
    metadata: {},
    created_by: TOMAS.id,
    created_at: daysAgo(12),
    updated_at: daysAgo(0),
    deleted_at: null,
  },
  {
    id: id("task", 4),
    project_id: PROJECT_ID,
    title: "Rebuild the navigation shell",
    description: "One shell for every product, with the sidebar state owned above the route.",
    status: "in_progress",
    priority: "high",
    stage: "execution",
    type: "feature",
    progress: 40,
    labels: ["ui"],
    assignee_ids: [MARCUS.id],
    parent_link: id("goal", 2),
    start_date: dateIn(-9),
    due_date: dateIn(8),
    deadline_tracking: true,
    metadata: {},
    created_by: MARCUS.id,
    created_at: daysAgo(9),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: id("task", 5),
    project_id: PROJECT_ID,
    title: "Document the component API conventions",
    description: "Compound components, controlled props, and when a slot beats a boolean.",
    status: "todo",
    priority: "medium",
    stage: "planning",
    type: "task",
    progress: 0,
    labels: ["docs"],
    assignee_ids: [ADA.id],
    parent_link: id("goal", 2),
    start_date: dateIn(3),
    due_date: dateIn(17),
    deadline_tracking: false,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
    deleted_at: null,
  },
  {
    id: id("task", 6),
    project_id: PROJECT_ID,
    title: "Consolidate the icon set",
    description: "The vendor licence for two families is unresolved, so the final set is blocked.",
    status: "blocked",
    priority: "medium",
    stage: "backlog",
    type: "chore",
    progress: 10,
    labels: ["blocked", "icons"],
    assignee_ids: [ADA.id],
    parent_link: null,
    start_date: dateIn(-4),
    due_date: dateIn(20),
    deadline_tracking: false,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(14),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
  {
    id: id("task", 7),
    project_id: PROJECT_ID,
    title: "Publish Storybook to staging",
    description: "Every merge deploys the library docs so design can review without a local build.",
    status: "todo",
    priority: "low",
    stage: "backlog",
    type: "task",
    progress: 0,
    labels: ["docs"],
    assignee_ids: [TOMAS.id],
    parent_link: id("goal", 2),
    start_date: null,
    due_date: dateIn(26),
    deadline_tracking: false,
    metadata: {},
    created_by: TOMAS.id,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    deleted_at: null,
  },
  {
    id: id("task", 8),
    project_id: PROJECT_ID,
    title: "Typography scale pass",
    description: "Collapse the eight ad-hoc sizes onto the four-step scale.",
    status: "done",
    priority: "medium",
    stage: "testing",
    type: "improvement",
    progress: 100,
    labels: ["tokens"],
    assignee_ids: [ADA.id],
    parent_link: id("goal", 1),
    start_date: dateIn(-20),
    due_date: dateIn(-10),
    deadline_tracking: true,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(20),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: id("task", 9),
    project_id: PROJECT_ID,
    title: "Accessibility sweep on the forms",
    description: "Labels, error wiring and focus order across every settings form.",
    status: "in_progress",
    priority: "critical",
    stage: "testing",
    type: "bug",
    progress: 55,
    labels: ["a11y"],
    assignee_ids: [LENA.id],
    parent_link: id("goal", 5),
    start_date: dateIn(-8),
    due_date: dateIn(4),
    deadline_tracking: true,
    metadata: {},
    created_by: LENA.id,
    created_at: daysAgo(8),
    updated_at: daysAgo(0),
    deleted_at: null,
  },
  {
    id: id("task", 10),
    project_id: PROJECT_ID,
    title: "Dashboard chart primitives",
    description: "One wrapper that owns axis, tooltip and empty behaviour for every chart.",
    status: "todo",
    priority: "high",
    stage: "planning",
    type: "feature",
    progress: 0,
    labels: ["charts"],
    assignee_ids: [TOMAS.id],
    parent_link: id("goal", 2),
    start_date: dateIn(6),
    due_date: dateIn(22),
    deadline_tracking: false,
    metadata: {},
    created_by: TOMAS.id,
    created_at: daysAgo(6),
    updated_at: daysAgo(6),
    deleted_at: null,
  },
  {
    id: id("task", 11),
    project_id: PROJECT_ID,
    title: "Retire the old grid system",
    description: "Delete the last two consumers, then drop the package.",
    status: "todo",
    priority: "low",
    stage: "backlog",
    type: "chore",
    progress: 0,
    labels: ["cleanup"],
    assignee_ids: [MARCUS.id],
    parent_link: null,
    start_date: null,
    due_date: dateIn(30),
    deadline_tracking: false,
    metadata: {},
    created_by: MARCUS.id,
    created_at: daysAgo(16),
    updated_at: daysAgo(16),
    deleted_at: null,
  },
  {
    id: id("task", 12),
    project_id: PROJECT_ID,
    title: "Motion guidelines draft",
    description: "Durations and easings for enter, exit and layout change.",
    status: "done",
    priority: "medium",
    stage: "review",
    type: "task",
    progress: 100,
    labels: ["docs"],
    assignee_ids: [ADA.id],
    parent_link: id("goal", 2),
    start_date: dateIn(-18),
    due_date: dateIn(-6),
    deadline_tracking: true,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(18),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
  {
    id: id("task", 13),
    project_id: PROJECT_ID,
    title: "Table virtualization spike",
    description: "Waiting on the grid retirement before the row renderer can be replaced.",
    status: "blocked",
    priority: "medium",
    stage: "execution",
    type: "improvement",
    progress: 25,
    labels: ["blocked", "performance"],
    assignee_ids: [PRIYA.id],
    parent_link: id("goal", 5),
    start_date: dateIn(-11),
    due_date: dateIn(13),
    deadline_tracking: false,
    metadata: {},
    created_by: PRIYA.id,
    created_at: daysAgo(11),
    updated_at: daysAgo(2),
    deleted_at: null,
  },
  {
    id: id("task", 14),
    project_id: PROJECT_ID,
    title: "Empty-state illustration set",
    description: "Eight illustrations covering the first-run surfaces in both themes.",
    status: "in_progress",
    priority: "low",
    stage: "execution",
    type: "task",
    progress: 30,
    labels: ["design"],
    assignee_ids: [ADA.id],
    parent_link: id("goal", 4),
    start_date: dateIn(-5),
    due_date: dateIn(19),
    deadline_tracking: false,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
];

const TASK_COMMENTS = [
  {
    id: id("taskComment", 1),
    task_id: id("task", 3),
    author_id: TOMAS.id,
    body: "Workspace shell is done; the settings screens are the last block. Should land inside the estimate.",
    attachments: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: id("taskComment", 2),
    task_id: id("task", 6),
    author_id: ADA.id,
    body: "Blocked on the vendor licence question. I'd rather wait than ship half a set and re-icon everything later.",
    attachments: [],
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: id("taskComment", 3),
    task_id: id("task", 9),
    author_id: LENA.id,
    body: "Three forms left. The invite dialog is the messy one — its errors are announced twice.",
    attachments: [],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: id("taskComment", 4),
    task_id: id("task", 13),
    author_id: PRIYA.id,
    body: "Spike proves the win is real — roughly 40% off first paint on the big tables. Parking until the grid is gone.",
    attachments: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
];

const ASSETS = [
  {
    id: id("asset", 1),
    project_id: PROJECT_ID,
    name: "apollo-token-sheet.pdf",
    media_type: "document",
    size_bytes: 1843200,
    url: "https://cdn.geiger.studio/demo/apollo-token-sheet.pdf",
    storage_path: "assets/apollo-token-sheet.pdf",
    tags: ["tokens", "reference"],
    owner: ADA.name,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
    deleted_at: null,
  },
  {
    id: id("asset", 2),
    project_id: PROJECT_ID,
    name: "nav-shell-motion.mp4",
    media_type: "video",
    size_bytes: 14680064,
    url: "https://cdn.geiger.studio/demo/nav-shell-motion.mp4",
    storage_path: "assets/nav-shell-motion.mp4",
    tags: ["motion", "ui"],
    owner: TOMAS.name,
    metadata: {},
    created_by: TOMAS.id,
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
    deleted_at: null,
  },
  {
    id: id("asset", 3),
    project_id: PROJECT_ID,
    name: "empty-board-light.png",
    media_type: "image",
    size_bytes: 284160,
    url: "https://cdn.geiger.studio/demo/empty-board-light.png",
    storage_path: "assets/empty-board-light.png",
    tags: ["illustration", "onboarding"],
    owner: ADA.name,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: id("asset", 4),
    project_id: PROJECT_ID,
    name: "empty-board-dark.png",
    media_type: "image",
    size_bytes: 271872,
    url: "https://cdn.geiger.studio/demo/empty-board-dark.png",
    storage_path: "assets/empty-board-dark.png",
    tags: ["illustration", "onboarding"],
    owner: ADA.name,
    metadata: {},
    created_by: ADA.id,
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: id("asset", 5),
    project_id: PROJECT_ID,
    name: "bundle-report-baseline.json",
    media_type: "document",
    size_bytes: 96408,
    url: "https://cdn.geiger.studio/demo/bundle-report-baseline.json",
    storage_path: "assets/bundle-report-baseline.json",
    tags: ["performance"],
    owner: PRIYA.name,
    metadata: {},
    created_by: PRIYA.id,
    created_at: daysAgo(13),
    updated_at: daysAgo(13),
    deleted_at: null,
  },
  {
    id: id("asset", 6),
    project_id: PROJECT_ID,
    name: "design-review-2026-08.m4a",
    media_type: "audio",
    size_bytes: 8912896,
    url: "https://cdn.geiger.studio/demo/design-review-2026-08.m4a",
    storage_path: "assets/design-review-2026-08.m4a",
    tags: ["review"],
    owner: SAM.name,
    metadata: {},
    created_by: SAM.id,
    created_at: daysAgo(22),
    updated_at: daysAgo(22),
    deleted_at: null,
  },
  {
    id: id("asset", 7),
    project_id: PROJECT_ID,
    name: "icon-audit-export.zip",
    media_type: "archive",
    size_bytes: 4194304,
    url: "https://cdn.geiger.studio/demo/icon-audit-export.zip",
    storage_path: "assets/icon-audit-export.zip",
    tags: ["icons", "audit"],
    owner: MARCUS.name,
    metadata: {},
    created_by: MARCUS.id,
    created_at: daysAgo(17),
    updated_at: daysAgo(17),
    deleted_at: null,
  },
  {
    id: id("asset", 8),
    project_id: PROJECT_ID,
    name: "contrast-matrix.csv",
    media_type: "document",
    size_bytes: 51200,
    url: "https://cdn.geiger.studio/demo/contrast-matrix.csv",
    storage_path: "assets/contrast-matrix.csv",
    tags: ["a11y", "tokens"],
    owner: LENA.name,
    metadata: {},
    created_by: LENA.id,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    deleted_at: null,
  },
];

// A fortnight of activity so the Overview's range filter has something to draw
// in every bucket. Actors are display names — normalizeActivityLog passes the
// column straight through.
const ACTIVITY_LOGS = [
  { level: "info", source: "tasks", actor: TOMAS.name, message: 'Moved task "Migrate tokens to CSS variables" to In Progress', days: 0.2 },
  { level: "warning", source: "issues", actor: LENA.name, message: 'Raised issue "Add a dark-mode contrast test" as critical', days: 0.6 },
  { level: "info", source: "issues", actor: ADA.name, message: 'Comment added to issue "Token values drift between light and dark"', days: 1.1 },
  { level: "info", source: "tasks", actor: LENA.name, message: 'Updated progress on "Accessibility sweep on the forms" to 55%', days: 1.5 },
  { level: "info", source: "milestones", actor: ADA.name, message: 'Milestone "Design system v2 — beta" is 50% complete', days: 2 },
  { level: "warning", source: "tasks", actor: ADA.name, message: 'Task "Consolidate the icon set" is blocked', days: 3 },
  { level: "info", source: "goals", actor: SAM.name, message: 'Goal "Reduce onboarding to three steps" flagged At Risk', days: 4 },
  { level: "info", source: "issues", actor: ADA.name, message: 'Resolved issue "Focus ring invisible on the primary button"', days: 5 },
  { level: "debug", source: "reporting", actor: PRIYA.name, message: "Bundle report generated (baseline recorded)", days: 6 },
  { level: "info", source: "tasks", actor: ADA.name, message: 'Completed task "Typography scale pass"', days: 8 },
  { level: "error", source: "grounding", actor: null, message: "Realtime channel dropped; reconnected after 4s", days: 10 },
  { level: "info", source: "team", actor: SAM.name, message: `${PEOPLE.length} members active on this project`, days: 12 },
  { level: "info", source: "assets", actor: MARCUS.name, message: 'Uploaded "icon-audit-export.zip"', days: 17 },
  { level: "info", source: "project", actor: ADA.name, message: "Project created", days: 120 },
];

const RESOURCE_ALLOCATIONS = [
  { member: ADA.name, role: "Design Lead", allocation: 80, status: "Active", starts: -60, ends: 45, notes: "Design system v2" },
  { member: MARCUS.name, role: "Engineering Lead", allocation: 60, status: "Active", starts: -60, ends: 45, notes: "Split with platform support" },
  { member: PRIYA.name, role: "Platform Engineer", allocation: 70, status: "Active", starts: -40, ends: 60, notes: "Performance budget work" },
  { member: TOMAS.name, role: "Frontend Engineer", allocation: 100, status: "Active", starts: -30, ends: 30, notes: "Fully allocated to the migration" },
  { member: LENA.name, role: "QA Engineer", allocation: 45, status: "Active", starts: -20, ends: 40, notes: "Also covering release testing" },
  { member: SAM.name, role: "Product Manager", allocation: 30, status: "Tentative", starts: 10, ends: 80, notes: "Onboarding rewrite planning" },
].map((row, index) => ({
  id: id("allocation", 1 + index),
  project_id: PROJECT_ID,
  member: row.member,
  role: row.role,
  allocation: row.allocation,
  status: row.status,
  starts_on: dateIn(row.starts),
  ends_on: dateIn(row.ends),
  notes: row.notes,
  metadata: {},
  created_by: ADA.id,
  created_at: daysAgo(40 - index),
  updated_at: daysAgo(10 - index),
  deleted_at: null,
}));

const EXTERNAL_LINKS = [
  {
    title: "Design system Figma",
    url: "https://figma.com/file/apollo-design-system",
    icon: "Figma",
    textColor: "#a78bfa",
    showOnTopbar: true,
    showOnDashboard: true,
  },
  {
    title: "Storybook",
    url: "https://storybook.geiger.studio",
    icon: "BookOpen",
    textColor: "#38bdf8",
    showOnTopbar: true,
    showOnDashboard: true,
  },
  {
    title: "Release notes",
    url: "https://geiger.studio/changelog",
    icon: "ScrollText",
    textColor: "#34d399",
    showOnTopbar: false,
    showOnDashboard: true,
  },
].map((link, index) => ({
  id: id("link", 1 + index),
  project_id: PROJECT_ID,
  title: link.title,
  url: link.url,
  icon: link.icon,
  metadata: {
    textColor: link.textColor,
    showOnTopbar: link.showOnTopbar,
    showOnDashboard: link.showOnDashboard,
    openInNewTab: true,
  },
  created_by: ADA.id,
  created_at: daysAgo(90 - index),
  updated_at: daysAgo(90 - index),
  deleted_at: null,
}));

// The project row itself. `organization_id` is load-bearing: Issues, Tasks,
// Work Queue and Reporting all resolve assignable people through
// listOrgMembers(project.organization_id).
export const DEMO_PROJECT = {
  id: PROJECT_ID,
  organization_id: DEMO_ORGANIZATION_ID,
  name: "Apollo Platform Redesign",
  slug: "apollo-platform-redesign",
  description:
    "Rebuild the product surface on the Apollo design system: one token set, one component library, and an onboarding flow a new account can finish in under five minutes.",
  logo_url: null,
  provider: "vercel",
  region: "iad1",
  status: "ACTIVE",
  tags: ["ACTIVE", "Design System"],
  created_by: ADA.id,
  metadata: { vault: {} },
  created_at: daysAgo(120),
  updated_at: daysAgo(0),
};

// The topbar bell is visible in the embed, so it gets a small inbox rather than
// an empty panel. Shapes mirror what notifications_dropdown.jsx reads.
const NOTIFICATIONS = [
  {
    type: "mention",
    icon: "AtSign",
    bgColor: "bg-indigo-500/10",
    iconColor: "text-indigo-400",
    title: "Ada mentioned you",
    description: 'In "Token values drift between light and dark" — can you confirm the dark pair?',
    days: 0.3,
    read: false,
  },
  {
    type: "discussion",
    icon: "MessageSquare",
    bgColor: "bg-emerald-500/10",
    iconColor: "text-emerald-400",
    title: "New reply in Design system v2",
    description: "Marcus replied about the navigation shell rebuild.",
    days: 1.4,
    read: false,
  },
  {
    type: "review",
    icon: "GitPullRequest",
    bgColor: "bg-amber-500/10",
    iconColor: "text-amber-400",
    title: "Review requested",
    description: 'Tomás requested your review on "Migrate tokens to CSS variables".',
    days: 2.6,
    read: true,
  },
];

// Keyed "<schema>.<table>" — one lookup serves both the `flow` schema and the
// shared `public` tables the app reads alongside it.
export const fixtures = {
  "public.projects": [DEMO_PROJECT],
  "public.flow_profiles": PEOPLE.map((person) => ({
    id: person.id,
    display_name: person.name,
    email: person.email,
    avatar_url: null,
    organization_id: DEMO_ORGANIZATION_ID,
  })),
  "public.flow_notifications": NOTIFICATIONS.map((note, index) => ({
    id: id("notification", 1 + index),
    user_id: ADA.id,
    project_id: PROJECT_ID,
    type: note.type,
    title: note.title,
    description: note.description,
    icon: note.icon,
    bg_color: note.bgColor,
    icon_color: note.iconColor,
    read: note.read,
    extra: null,
    time: at(-note.days),
  })),

  "flow.project_members": PROJECT_MEMBERS,
  "flow.objectives": OBJECTIVES,
  "flow.goals": GOALS,
  "flow.milestones": MILESTONES,
  "flow.issues": ISSUES,
  "flow.issue_comments": ISSUE_COMMENTS,
  "flow.tasks": TASKS,
  "flow.task_comments": TASK_COMMENTS,
  "flow.assets": ASSETS,
  "flow.activity_logs": ACTIVITY_LOGS.map((log, index) => ({
    id: id("log", 1 + index),
    project_id: PROJECT_ID,
    level: log.level,
    source: log.source,
    actor: log.actor,
    message: log.message,
    detail: null,
    metadata: {},
    occurred_at: at(-log.days),
    created_by: null,
    created_at: at(-log.days),
    updated_at: at(-log.days),
    deleted_at: null,
  })),
  "flow.resource_allocations": RESOURCE_ALLOCATIONS,
  "flow.external_links": EXTERNAL_LINKS,
};
