import {
  LayoutDashboard,
  GitBranch,
  Database,
  Activity,
  Settings,
  ShieldCheck,
  Users,
  UsersRound,
  Settings2,
  BarChart3,
  Sliders,
  CheckSquare,
  BriefcaseBusiness,
  SlidersHorizontal,
  Flag,
  LucideFileImage,
  Target,
  LucideSquareChevronRight,
  Key,
  LucideMousePointer2,
  Calendar,
  LucidePlus,
  LucidePackagePlus,
  Waypoints,
  Radio,
  Link2,
  ExternalLink,
} from "lucide-react";

export const projectNav = [
  { title: "Overview", icon: LayoutDashboard },
  { title: "Issues", icon: GitBranch },
  { title: "Tasks", icon: CheckSquare },
  { title: "Work Queue", icon: BriefcaseBusiness },
  { title: "Grounding", icon: Radio },
  { title: "Planning", icon: Waypoints },
  { title: "Projections", icon: LucideSquareChevronRight },
  { title: "Milestones", icon: Flag, badge: "3" },
  { title: "Goals", icon: Target },
  { title: "Reporting", icon: BarChart3 },
  { title: "Objectives", icon: Database },
  { title: "Assets", icon: LucideFileImage },
  { title: "Logs", icon: Activity },
  { title: "Team", icon: Users, badge: "7" },
  { title: "Resource Allocation", icon: UsersRound },
  { title: "Vault", icon: Key },
  { title: "Externals", icon: ExternalLink },
  { title: "Security", icon: ShieldCheck },
  { title: "Settings", icon: Settings, hasSubmenu: true },
];

export const settingsNav = [
  { title: "General", icon: Settings2 },
  { title: "Connections", icon: Link2 },
  { title: "Customs", icon: SlidersHorizontal },
  { title: "Add-ons", icon: LucidePackagePlus },
  { title: "Usage", icon: BarChart3 },
  { title: "Advanced", icon: Sliders },
  { title: "Enterprise", icon: LucideMousePointer2 },
];
